language: go
sudo: false
dist: trusty
go:
  - 1.9.5
os:
  - linux
  - osx
matrix:
  fast_finish: true
install:
  - go get github.com/magefile/mage
  - mage -v vendor
script:
  - mage -v hugoRace
  - mage -v check
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_deploy:
  - git remote set-url origin ${GIT_URL}
  - git fetch origin gh-pages:remotes/origin/gh-pages
  - git worktree add -B gh-pages public origin/gh-pages
  - ./hugo -t "hugo-theme-cactus-plus"
deploy:
  github_token: $GITHUB_TOKEN
  provider: script
  script: chmod u+x deploy.sh && sh ./deploy.sh
  on:
    branch: master