language: go
go:
  - 1.7
env:
  global:
    - GIT_AUTHOR_EMAIL=32930281+gtongy@users.noreply.github.com
    - GIT_AUTHOR_NAME=gtongy
    - HUGO_VERSION=0.36.1
    - GIT_URL=https://${GITHUB_TOKEN}@github.com/gtongy/chick-tack.git
install:
  - go get -v github.com/spf13/hugo
before_deploy:
  - git remote set-url origin ${GIT_URL}
  - git fetch origin gh-pages:remotes/origin/gh-pages
  - git worktree add -B gh-pages public origin/gh-pages
  - hugo -t "hugo-theme-cactus-plus"
deploy:
  github_token: $GITHUB_TOKEN
  provider: script
  script: chmod u+x deploy.sh && sh ./deploy.sh
  on:
    branch: master