os:
  - linux
env:
  global:
    - GIT_AUTHOR_EMAIL=32930281+gtongy@users.noreply.github.com
    - GIT_AUTHOR_NAME=gtongy
script:
  - ./binaries/hugo version
  - chmod u+x deploy.sh && sh ./deploy.sh
before_install:
  - openssl aes-256-cbc -K $encrypted_8c176495c53a_key -iv $encrypted_8c176495c53a_iv -in travis-rsa.enc -out travis-rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email ${GIT_AUTHOR_EMAIL}
  - git config --global user.name ${GIT_AUTHOR_NAME}