baseurl = "https://gtongy.github.io/chick-tack/"
canonifyurls = true
<<<<<<< HEAD
languageCode = "ja"
=======
languageCode = "en"
>>>>>>> 623e0682c71fb2dd0773ea5eb50427ff4d232f00
title = "Chick Tack - 駆け出しPHPerエンジニアの技術ブログです"
theme = "hugo-theme-cactus-plus"
# googleAnalytics = "UA-89451571-2"
pygmentscodefences = true
pygmentsstyle = "monokai"
hasCJKLanguage = true
SummaryLength = 150
[params]
	description = "Chick Tack - Chick Tackは駆け出しPHPerエンジニアの技術ブログです。日々調べて気になったこと、新しく知ったことを中心につらつらと書き連ねます。"
<<<<<<< HEAD
	about = ""
	showLatestPosts = true
	enableShare = true
=======
>>>>>>> 623e0682c71fb2dd0773ea5eb50427ff4d232f00
	author = "gtongy"
	enableTwitterCard = true
	twitter = "gtongy1"
	enableSummary = true
	useDescriptionReplaceSummary = false
	iconFont = "font-awesome"
	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
[social]
	github-square = "https://github.com/gtongy"
[permalinks]
	post = "/:year/:title/"