baseurl = "chick-tack.com"
languageCode = "en"
title = "Chick Tack"
theme = "hugo-theme-cactus-plus"
[params]
	author = "gtongy"
	description = "ひよっこの道のり"
	bio = "ひよっこの道のり"
	enableSummary = true
	useDescriptionReplaceSummary = false
	iconFont = "font-awesome"
[social]
	github-square = "https://github.com/gtongy"

