baseurl = "https://gtongy.github.io/chick-tack/"
canonifyurls = true
languageCode = "en"
title = "Chick Tack"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-89451571-2"
pygmentscodefences = true
pygmentsstyle = "monokai"
hasCJKLanguage = true
SummaryLength = 150
[params]
	author = "gtongy"
	enableSummary = true
	useDescriptionReplaceSummary = false
	iconFont = "font-awesome"
	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
[social]
	github-square = "https://github.com/gtongy"

