baseurl = "https://chick-tack.blog/"
canonifyurls = true
languageCode = "ja"
title = "Chick Tack - 駆け出しPHPerエンジニアの技術ブログです"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-89451571-2"
pygmentscodefences = true
pygmentsstyle = "monokai"
hasCJKLanguage = true
SummaryLength = 150
[params]
	description = "Chick Tack - Chick Tackは駆け出しPHPerエンジニアの技術ブログです。日々調べて気になったこと、新しく知ったことを中心につらつらと書き連ねます。"
	showLatestPosts = true
	enableShare = true
	author = "gtongy"
	enableTwitterCard = true
	twitter = "gtongy1"
	enableSummary = true
	useDescriptionReplaceSummary = false
	iconFont = "font-awesome"
	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	customCSS = ["css/adsbygoogle.css", "css/_style.css"]
[params.adsense]
	client = "ca-pub-5193360380364380"
	inArticleSlot = "1435944754"
[social]
	github-square = "https://github.com/gtongy"
[permalinks]
	post = "/:year/:title/"
